In [1]:
import requests
import pandas as pd
from io import StringIO

URLS = {
    "학생식당": "https://www.kumoh.ac.kr/ko/restaurant01.do",
    "교직원식당": "https://www.kumoh.ac.kr/ko/restaurant02.do",
    "분식당": "https://www.kumoh.ac.kr/ko/restaurant04.do",
}

def fetch_html(url: str) -> str:
    res = requests.get(url, timeout=15)
    res.raise_for_status()
    res.encoding = "utf-8"
    return res.text

print("대상 식당:", ", ".join(URLS.keys()))

/Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

대상 식당: 학생식당, 교직원식당, 분식당

In [2]:
# 각 식당 URL에서 식단표를 읽어 DataFrame으로 저장
menus = {}

for name, url in URLS.items():
    html = fetch_html(url)
    tables = pd.read_html(StringIO(html))  # FutureWarning 회피

    if not tables:
        print(f"[{name}] 테이블 없음")
        continue

    df = tables[0].copy()
    df.columns = [str(c).strip() for c in df.columns]

    # 셀 텍스트의 줄바꿈/중복 공백 정리
    df = df.replace(r"\s+", " ", regex=True)
    menus[name] = df

    print(f"[{name}] 테이블 {len(tables)}개 발견 / shape={df.shape}")

# 출력 생략 방지 옵션
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# 개별 결과 확인
student_df = menus.get("학생식당")
staff_df = menus.get("교직원식당")
snack_df = menus.get("분식당")

print("\n=== 학생식당 (전체) ===")
display(student_df)

print("\n=== 교직원식당 (전체) ===")
display(staff_df)

print("\n=== 분식당 (전체) ===")
display(snack_df)

[학생식당] 테이블 1개 발견 / shape=(2, 7)
[교직원식당] 테이블 1개 발견 / shape=(2, 7)
[분식당] 테이블 1개 발견 / shape=(1, 7)

=== 학생식당 (전체) ===

,월(03.30),화(03.31),수(04.01),목(04.02),금(04.03),토(04.04),일(04.05)
0,조식 [천원의 아침밥] *재학생만 해당 08:20~10:00 든든한제육&돈까스도시락,조식 [천원의 아침밥] *재학생만 해당 08:20~10:00 새콤달콤유부초밥 에그치즈토마토샌드위치 홈요거트,조식 [천원의 아침밥] *재학생만 해당 08:20~10:00 콰트로고기정찬도시락,조식 [천원의 아침밥] *재학생만 해당 08:20~10:00 한돈가츠동덮밥도시락 딸기요플레,조식 [천원의 아침밥] *재학생만 해당 08:20~10:00 다찬스페셜정식도시락 요구르트,조식 식당 운영 없음,조식 식당 운영 없음
1,중식 [정식: 4500원] 11:30~13:30 김밥맛볶음밥 팽이버섯된장국 김구이 계란장조림 실곤약야채무침 맛김치,중식 [정식: 4500원] 11:30~13:30 제육덮밥 무채맑은국 미니메밀전병구이 콩나물무침 맛김치,중식 [정식: 4500원] 11:30~13:30 쌀밥 닭곰탕 연두부/양념장 볶음멸치조림 마늘종장아찌무침 깍두기,중식 [정식: 4500원] 11:30~13:30 쌀밥 돼지찌개 감자크로켓 오이생채 어묵채볶음 맛김치,중식 [정식: 4500원] 11:30~13:30 쌀밥 짬뽕순두부찌개 한입돈까스 다시마부각 쥐어채볶음 깍두기,중식 식당 운영 없음,중식 식당 운영 없음

=== 교직원식당 (전체) ===

,월(03.30),화(03.31),수(04.01),목(04.02),금(04.03),토(04.04),일(04.05)
0,중식 [정식: 6000원] 11:30~13:30 잡곡밥 매운순대국 두부양념구이 너비아니조림 깻잎지 깍두기,중식 [정식: 6000원] 11:30~13:30 잡곡밥 참치김치찌개 양파돈가스 실곤약야채무침 애느타리버섯구이 락교단무지무침,중식 [정식: 6000원] 11:30~13:30 콩나물밥 열무된장국 돈육오징어볶음 감자크로켓 솎음배추생채 알타리김치 초코쌀뻥,중식 [정식: 6000원] 11:30~13:30 산채비빔밥 계란야채국 미트볼조림 도토리묵무침 배추김치 포켓팝콘,중식 [정식: 6000원] 11:30~13:30 잡곡밥 옹심이만두미역국 순살치킨강정 어묵야채볶음 무샐러리장아찌 배추김치,중식 식당 운영 없음,중식 식당 운영 없음
1,석식 [정식: 6000원] 17:00~18:30 닭갈비덮밥 팽이버섯장국 메밀전병구이 천사채황도샐러드 오이부추생채 배추김치,석식 [정식: 6000원] 17:00~18:30 잡곡밥 물떡어묵국 생선까스 볶은멸치조림 고사리들깨볶음 얼갈이시저샐러드 깍두기,석식 [정식: 6000원] 17:00~18:30 김치볶음밥 유부장국 치킨너겟/소스 맛김구이 참나물겉절이 고들빼기무침 깍두기,석식 [정식: 6000원] 17:00~18:30 잡곡밥 부대찌개 김말이튀김강정 쥐어채볶음 시금치무침 깍두기 캔매실음료,석식 [정식: 6000원] 17:00~18:30 잡곡밥 돼지찌개 오징어미나리무침 야채계란찜 해쉬브라운감자구이 배추김치,석식 식당 운영 없음,석식 식당 운영 없음

=== 분식당 (전체) ===

,월(03.30),화(03.31),수(04.01),목(04.02),금(04.03),토(04.04),일(04.05)
0,일품요리 11:00~14:00 16:00~18:30 등촌샤브칼국수 하이라이스&우리쌀치킨강정 라면류 돈가스류,일품요리 11:00~14:00 16:00~18:30 장터국밥 날치알참치회덮밥 라면류 돈가스류,일품요리 11:00~14:00 16:00~18:30 치킨크림스튜우동 불닭덮밥 라면류 돈가스류,일품요리 11:00~14:00 16:00~18:30 탄탄면 차돌국물떡볶이 라면류 돈가스류,일품요리 11:00~14:00 16:00~18:30 짜계치 모듬까스 라면류 돈가스류,일품요리 식당 운영 없음,일품요리 식당 운영 없음

In [3]:
# 필요 시 주석 해제 후 1회 실행
%pip install requests beautifulsoup4 lxml pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (4.14.3)
Requirement already satisfied: lxml in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (6.0.2)
Requirement already satisfied: pandas in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: pytz>=2020.1 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: numpy>=1.22.4 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/gimhyeonjin/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.